server {
    listen 8080;
    server_name localhost;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # This try_files directive ensures that React Router works correctly on reload
        try_files $uri $uri/ /index.html;
    }
}
